nopCommerce/Presentation/Nop.Web/Administration/Controllers/ReturnRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Nop.Admin.Infrastructure.Cache;
using Nop.Admin.Models.Catalog;
using Nop.Admin.Models.Orders;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Localization;
using Nop.Core.Domain.Media;
using Nop.Core.Domain.Orders;
using Nop.Services.Catalog;
using Nop.Services.Common;
using Nop.Services.Customers;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Shipping;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Kendoui;

namespace Nop.Admin.Controllers
{
    public partial class ReturnRequestController : BaseAdminController
    {
        #region Fields

        private readonly IReturnRequestService _returnRequestService;
        private readonly IOrderService _orderService;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly ICustomerService _customerService;
        private readonly ICustomerAttributeParser _customerAttributeParser;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly IWorkflowMessageService _workflowMessageService;
        private readonly LocalizationSettings _localizationSettings;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IPermissionService _permissionService;
        private readonly IShippingService _shippingService;
        private readonly CatalogSettings _catalogSettings;
        private readonly IProductService _productService;
        private readonly MediaSettings _mediaSettings;
        private readonly IPictureService _pictureService;

        #endregion Fields

        #region Constructors

        public ReturnRequestController(IReturnRequestService returnRequestService,
            IOrderService orderService,
            ICustomerAttributeParser customerAttributeParser,
            ICustomerService customerService,
            IDateTimeHelper dateTimeHelper,
            ILocalizationService localizationService,
            IWorkContext workContext,
            IWorkflowMessageService workflowMessageService,
            LocalizationSettings localizationSettings,
            ICustomerActivityService customerActivityService, 
            IPermissionService permissionService,
            IShippingService shippingService,
            CatalogSettings catalogSettings,
            IProductService productService,
            MediaSettings mediaSettings,
            IPictureService pictureService)
        {
            this._returnRequestService = returnRequestService;
            this._orderService = orderService;
            this._customerAttributeParser = customerAttributeParser;
            this._customerService = customerService;
            this._dateTimeHelper = dateTimeHelper;
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._workflowMessageService = workflowMessageService;
            this._localizationSettings = localizationSettings;
            this._customerActivityService = customerActivityService;
            this._permissionService = permissionService;
            this._shippingService = shippingService;
            this._catalogSettings = catalogSettings;
            this._productService = productService;
            this._mediaSettings = mediaSettings;
            this._pictureService = pictureService;
        }

        #endregion

        #region Utilities

        [NonAction]
        protected virtual bool PrepareReturnRequestModel(ReturnRequestModel model, ReturnRequest returnRequest, bool excludeProperties)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            if (returnRequest == null)
                throw new ArgumentNullException("returnRequest");

            OrderItem orderItem = null;
            if (returnRequest.OrderItemId.HasValue)
            {
                orderItem = _orderService.GetOrderItemById(returnRequest.OrderItemId.Value);
            }
            //if (orderItem == null)
            //    return false;

            model.Id = returnRequest.Id;

            if (returnRequest.RequestedAction == "Repair")
            {
                model.ProductId = returnRequest.ProductId;
                model.ProductName = returnRequest.ProductDetails;
            }
            else if (orderItem != null)
            {
                model.ProductId = orderItem.ProductId;
                model.ProductName = orderItem.Product.Name;
                model.OrderId = orderItem.OrderId;
            }

            model.CustomerId = returnRequest.CustomerId.Value;
            var customer = returnRequest.Customer;
            model.Customer = new Models.Customers.CustomerModel {
                FullName = customer.GetFullName(),
                CustomerNumber = customer.CustomerNumber,
                Email = customer.IsRegistered() ? customer.Email : _localizationService.GetResource("Admin.Customers.Guest")
            };
            
            model.Quantity = returnRequest.Quantity;
            model.ReturnRequestStatusStr = returnRequest.ReturnRequestStatus.GetLocalizedEnum(_localizationService, _workContext);
            model.CreatedOn = _dateTimeHelper.ConvertToUserTime(returnRequest.CreatedOnUtc, DateTimeKind.Utc);
            
            if (!excludeProperties)
            {
                model.ReasonForReturn = returnRequest.ReasonForReturn;
                model.RequestedAction = returnRequest.RequestedAction;
                model.CustomerComments = returnRequest.CustomerComments;
                model.StaffNotes = returnRequest.StaffNotes;
                model.ReturnRequestStatusId = returnRequest.ReturnRequestStatusId;
            }

            //model is successfully prepared
            return true;
        }

        #endregion

        #region "Repair Requests"

        [HttpPost]
        public ActionResult AuthorizeRepairRequest(int repairRequestId) {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            var repairRequest = _returnRequestService.GetReturnRequestById(repairRequestId);

            if (repairRequest != null && repairRequest.ReturnRequestStatus != ReturnRequestStatus.Authorized) {
                var currentDate = DateTime.Now;

                // get repair requests for the same day at the same warehouse
                var currentRepairRequests = _returnRequestService.SearchReturnRequests(createdOn: currentDate.Date, warehouseId: repairRequest.WarehouseId);

                var sequence = currentRepairRequests.Where(w => !String.IsNullOrEmpty(w.AuthorizationNumber)).Count() + 1;

                repairRequest.ReturnRequestStatus = ReturnRequestStatus.Authorized;
                repairRequest.AuthorizationNumber = $"{currentDate.ToString("yyyyddMM")}-{repairRequest.Warehouse.Code}-{sequence}";

                _returnRequestService.UpdateReturnRequest(repairRequest);

                _workflowMessageService.SendRepairRequestAuthorizedNotification(repairRequest, _localizationSettings.DefaultAdminLanguageId);
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public ActionResult CancelRepairRequest(int repairRequestId) {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            var repairRequest = _returnRequestService.GetReturnRequestById(repairRequestId);

            if (repairRequest != null && repairRequest.ReturnRequestStatus != ReturnRequestStatus.Cancelled) {
                repairRequest.ReturnRequestStatus = ReturnRequestStatus.Cancelled;

                _returnRequestService.UpdateReturnRequest(repairRequest);
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public ActionResult CompleteRepairRequest(int repairRequestId) {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            var repairRequest = _returnRequestService.GetReturnRequestById(repairRequestId);

            if (repairRequest != null && repairRequest.ReturnRequestStatus != ReturnRequestStatus.Complete) {
                repairRequest.ReturnRequestStatus = ReturnRequestStatus.Complete;

                _returnRequestService.UpdateReturnRequest(repairRequest);

                _workflowMessageService.SendRepairRequestCompleteNotification(repairRequest, _localizationSettings.DefaultAdminLanguageId);
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpGet]
        public ActionResult GetRepairRequestForm(int? repairRequestId) {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            ReturnRequest repairRequest = null;

            if (repairRequestId.HasValue) {
                repairRequest = _returnRequestService.GetReturnRequestById(repairRequestId.Value);
            }

            var model = PrepareRepairRequestModel(repairRequest);

            return PartialView("_CreateOrUpdateRepairRequest", model);
        }
        [HttpPost]
        public ActionResult InboundRepairRequest(int repairRequestId, string trackingNumberInbound) {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

nopCommerce/Presentation/Nop.Web/Administration/Views/ReturnRequest/Edit.cshtml
@model ReturnRequestModel
@{
    //page title
    ViewBag.Title = T("Admin.ReturnRequests.EditReturnRequestDetails").Text;
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="section-header">
        <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-sales.png")" alt="" />
            @T("Admin.ReturnRequests.EditReturnRequestDetails") @Html.ActionLink("(" + T("Admin.ReturnRequests.BackToList") + ")", "List")
        </div>
        <div class="options">
            <input type="submit" name="notify-customer" class="k-button" value="@T("Admin.ReturnRequests.NotifyCustomer")" />
            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
            <input type="submit" name="save-continue" class="k-button" value="@T("Admin.Common.SaveContinue")" />
            <span id="returnrequest-delete" class="k-button">@T("Admin.Common.Delete")</span>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}
@Html.DeleteConfirmation("returnrequest-delete")

nopCommerce/Presentation/Nop.Web/Administration/Views/ReturnRequest/List.cshtml
@{
    var defaultGridPageSize = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;

    //page title
    ViewBag.Title = T("Admin.ReturnRequests").Text;
}
@Html.AntiForgeryToken()
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-sales.png")" alt="" />
        @T("Admin.ReturnRequests")
    </div>
    <div class="options">
    </div>
</div>
<table class="adminContent">
    <tr>
        <td>
            <div id="returnrequests-grid"></div>

            <script>
                $(document).ready(function() {
                    $("#returnrequests-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("List", "ReturnRequest"))",
                                    type: "POST",
                                    dataType: "json",
                                    data: addAntiForgeryToken
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors"
                            },
                            error: function(e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            pageSize: @(defaultGridPageSize),
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            pageSizes: [@(gridPageSizes)]
                        },
                        editable: {
                            confirmation: false,
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [
                            {
                                field: "Id",
                                title: "@T("Admin.ReturnRequests.Fields.ID")",
                                width: 50
                            }, {
                                field: "ProductName",
                                title: "@T("Admin.ReturnRequests.Fields.Product")",
                                width: 200,
                                template: '<a href="@Url.Content("~/Admin/Product/Edit/")#=ProductId#">#:ProductName#</a>'
                            }, {
                                field: "Quantity",
                                title: "@T("Admin.ReturnRequests.Fields.Quantity")",
                                width: 100
                            }, {
                                field: "CustomerId",
                                title: "@T("Admin.ReturnRequests.Fields.Customer")",
                                width: 200,
                                template: '<a href="@Url.Content("~/Admin/Customer/Edit/")#=CustomerId#">#:CustomerInfo#</a>'
                            }, {
                                field: "OrderId",
                                title: "@T("Admin.ReturnRequests.Fields.Order")",
                                width: 200,
                                template: '<a href="@Url.Content("~/Admin/Order/Edit/")#=OrderId#">#=OrderId# - @T("Admin.Common.View")</a>'
                            }, {
                                field: "ReturnRequestStatusStr",
                                title: "@T("Admin.ReturnRequests.Fields.Status")",
                                width: 100
                            }, {
                                field: "CreatedOn",
                                title: "@T("Admin.ReturnRequests.Fields.CreatedOn")",
                                width: 100,
                                type: "date",
                                format: "{0:G}"
                            }, {
                                field: "Id",
                                title: "@T("Admin.Common.Edit")",
                                width: 100,
                                template: '<a href="Edit/#=Id#">@T("Admin.Common.Edit")</a>'
                            }
                        ]
                    });
                });
            </script>
        </td>
    </tr>
</table>

nopCommerce/Presentation/Nop.Web/Administration/Views/ReturnRequest/PrintRepairRequest.cshtml
@model RepairRequestModel

@{
    Layout = "~/Administration/Views/Shared/_PrintLayout.cshtml";
}

<div>
    <h5>Customer Information:</h5>
    <div style="margin-left: 15px;">
        <div>@Model.CustomerName</div>
        <div>@Model.CustomerCompany</div>
        <div><a href="mailto:@Model.CustomerEmail">@Model.CustomerEmail</a></div>
        <div><a href="callto:@Model.CustomerPhoneNumber">@Model.CustomerPhoneNumber</a></div>
    </div>
    <br />
    <h5>Product Information:</h5>
    <div style="margin-left: 15px;">
        <table class="table">
            <tr>
                <td style=" border-width: 0; width: 200px;"><img id="ImageProduct" class="img-thumbnail img-responsive" src="@Model.ProductPictureUrl" style="width: 200px;" /></td>
                <td style="border-width: 0;">
                    <h4 class="media-heading"><a id="LinkProduct" href="" target="_blank">@Model.ProductName</a></h4>
                    <div>Sku: #<span id="ProductSku">@Model.ProductSku</span></div>
                </td>
            </tr>
            <tr>
                <td class="text-right" style="border-width: 0;"><b>Customer Comments:</b></td>
                <td style="border-width: 0;">@Model.CustomerComments</td>
            </tr>
        </table>
    </div>
    <br />
    <h5>Repair Information:</h5>
    <div style="margin-left: 15px;">
        <table class="table">
            <tr>
                <td class="text-right" style="border-width: 0; width: 200px;"><b>Created On:</b></td>
                <td style="border-width: 0;">@Model.DateCreated.Value.ToShortDateString()</td>
            </tr>
            <tr>
                <td class="text-right" style="border-width: 0;"><b>Warehouse:</b></td>
                <td style="border-width: 0;">@Model.SelectedWarehouseName</td>
            </tr>
            <tr>
                <td class="text-right" style="border-width: 0;"><b>Repair Notes:</b></td>
                <td style="border-width: 0;">@Model.StaffNotes</td>
            </tr>
            <tr>
                <td class="text-right" style="border-width: 0;"><b>Authorization #:</b></td>
                <td style="border-width: 0;">@Model.AuthorizationNumber</td>
            </tr>
            <tr>
                <td class="text-right" style="border-width: 0;"><b>Status:</b></td>
                <td style="border-width: 0;">@Model.Status</td>
            </tr>
            <tr>
                <td class="text-right" style="border-width: 0;"><b>In-Tracking #:</b></td>
                <td style="border-width: 0;"><a href="https://www.ups.com/track?loc=null&tracknum=@Model.TrackingNumberInbound">@Model.TrackingNumberInbound</a></td>
            </tr>
            <tr>
                <td class="text-right" style="border-width: 0;"><b>Out-Tracking #:</b></td>
                <td style="border-width: 0;"><a href="https://www.ups.com/track?loc=null&tracknum=@Model.TrackingNumberOutbound">@Model.TrackingNumberOutbound</a></td>
            </tr>
        </table>
    </div>
</div>

nopCommerce/Presentation/Nop.Web/Administration/Views/ReturnRequest/RepairRequests.cshtml
@model RepairRequestsListModel

@{
    var defaultGridPageSize = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;

    //page title
    ViewBag.Title = T("Admin.RepairRequests").Text;
}

@Html.AntiForgeryToken()

<div class="container-fluid padding-0">
    <div class="row">
        <div class="col-md-6"><h4><span class="glyphicon glyphicon-wrench offset-right-10"></span> Repair Requests Log</h4></div>
        <div class="col-md-6 text-right">
            <a id="ButtonNewRepairRequest" href="#" class="btn btn-sm btn-info">New Repair Request</a>
        </div>
    </div>
</div>

<form id="FormSearch" class="form-horizontal">
    <div class="well">
        <div class="form-group">
            <div class="col-sm-1 control-label">@Html.LabelFor(model => model.RepairRequestsSearchModel.Customer, "Customer")</div>
            <div class="col-sm-2">
                @Html.TextBoxFor(model => model.RepairRequestsSearchModel.Customer, new { @class = "form-control" })
                @Html.HiddenFor(model => model.RepairRequestsSearchModel.CustomerId)
            </div>
            <div class="col-sm-1 control-label">@Html.LabelFor(model => model.RepairRequestsSearchModel.Customer, "Warehouse")</div>
            <div class="col-sm-2">@Html.DropDownListFor(model => model.RepairRequestsSearchModel.WarehouseId, Model.RepairRequestsSearchModel.Warehouses, new { @class = "form-control" })</div>
            <div class="col-sm-1 control-label">@Html.LabelFor(model => model.RepairRequestsSearchModel.AuthorizationNumber, "Authorization #")</div>
            <div class="col-sm-2">@Html.TextBoxFor(model => model.RepairRequestsSearchModel.AuthorizationNumber, new { @class = "form-control" })</div>
        </div>
        <div class="form-group">
            <div class="col-sm-1 control-label">@Html.LabelFor(model => model.RepairRequestsSearchModel.Statuses, "Product")</div>
            <div class="col-sm-2">@Html.TextBoxFor(model => model.RepairRequestsSearchModel.Product, new { @class = "form-control" })</div>
            <div class="col-sm-1 control-label">@Html.LabelFor(model => model.RepairRequestsSearchModel.Statuses, "Status")</div>
            <div class="col-sm-8" style="margin-top: 6px;">
                @foreach (var status in Model.RepairRequestsSearchModel.Statuses) {
                    <span style="margin-right: 15px;"><input id="RepairRequestsSearchModel_Statuses" @(status.Selected ? "checked" : "") style="margin-right: 5px;" type="checkbox" value="@status.Value" />@status.Text</span>
                }
            </div>
        </div>
        <hr />
        <div class="form-group">
            <div class="col-sm-1 control-label"></div>
            <div class="col-sm-11">
                <button type="button" id="buttonSearch" class="btn btn-sm btn-primary" value="@T("Admin.Common.Search")"><span class="glyphicon glyphicon-search" style="margin-right: 5px;"></span>@T("Admin.Common.Search")</button>
                <button type="button" id="buttonResetSearch" class="btn btn-sm btn-danger" value="Reset">Reset</button>
            </div>
        </div>
    </div>
</form>

<table class="adminContent">
    <tr>
        <td>
            <div id="returnrequests-grid"></div>
            <script type="text/x-kendo-template" id="productTemplate">
                # if (ProductId != null && ProductId != ''){ #
                    <a href='@Url.Content("~/Admin/Product/Edit/")#=ProductId#'>#:ProductName#</a>
                # } else { #
                    #:ProductName#
                # } #
            </script>
            <script type="text/x-kendo-template" id="trackingNumberInboundTemplate">
                # if (TrackingNumberInbound != null && TrackingNumberInbound != ''){ #
                    <a href="https://www.ups.com/track?loc=null&tracknum=#=TrackingNumberInbound#" target="_blank">#:TrackingNumberInbound#</a>
                # } else { #
                    N/A
                # } #
            </script>
            <script type="text/x-kendo-template" id="trackingNumberOutboundTemplate">
                # if (TrackingNumberOutbound != null && TrackingNumberOutbound != ''){ #
                    <a href="https://www.ups.com/track?loc=null&tracknum=#=TrackingNumberOutbound#" target="_blank">#:TrackingNumberOutbound#</a>
                # } else { #
                    N/A
                # } #
            </script>
        </td>
    </tr>
</table>

<div id="ModalRepairRequest" class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Repair Request</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("CreateRepairRequest", "RepairRequest", FormMethod.Post, new { @autocomplete = "chrome-off", @class = "form-horizontal", @id = "FormSubmitRepairRequest" })) {
                    @Html.AntiForgeryToken()
                    <div id="ContainerRepairRequest"></div>
                }
            </div>
            <div class="modal-footer">
                <div id="ModalRepairRequestMessageContainer"></div>
                <button id="ButtonCloseRepairRequest" data-dismiss="modal" type="button" class="btn btn-danger pull-left">Close</button>
                <button id="ButtonSubmitAndAuthorizeRepairRequest" type="button" class="btn btn-success">Save &amp; Authorize</button>
                <button id="ButtonSubmitRepairRequest" type="button" class="btn btn-success">Save</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="module">
    import RepairRequestsListController from '/Administration/Scripts/Views/Order/RepairRequests/repairRequestsListController.js';
    const repairRequestsListController = new RepairRequestsListController();
</script>

nopCommerce/Presentation/Nop.Web/Administration/Views/ReturnRequest/_CreateOrUpdate.cshtml
@model ReturnRequestModel
@using Nop.Core.Domain.Orders;
@Html.ValidationSummary(false)
@Html.HiddenFor(model => model.Id)
<table class="adminContent">
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.Id):
        </td>
        <td class="adminData">
            @Model.Id
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.OrderId):
        </td>
        <td class="adminData">
            @Html.ActionLink(T("Admin.Common.View").Text, "Edit", "Order", new { id = Model.OrderId }, new { })
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.CustomerId):
        </td>
        <td class="adminData">
            @Html.ActionLink(Model.CustomerInfo, "Edit", "Customer", new { id = Model.CustomerId }, new { })
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.ProductName):
        </td>
        <td class="adminData">
            @Html.ActionLink(Model.ProductName, "Edit", "Product", new { id = Model.ProductId }, new { })
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.Quantity):
        </td>
        <td class="adminData">
            @Html.EditorFor(model => model.Quantity)
            @Html.ValidationMessageFor(model => model.Quantity)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.ReturnRequestStatusId):
        </td>
        <td class="adminData">
            @Html.DropDownListFor(model => model.ReturnRequestStatusId, ((ReturnRequestStatus)Model.ReturnRequestStatusId).ToSelectList())
            @Html.ValidationMessageFor(model => model.ReturnRequestStatusId)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.ReasonForReturn):
        </td>
        <td class="adminData">
            @Html.EditorFor(model => model.ReasonForReturn)
            @Html.ValidationMessageFor(model => model.ReasonForReturn)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.RequestedAction):
        </td>
        <td class="adminData">
            @Html.EditorFor(model => model.RequestedAction)
            @Html.ValidationMessageFor(model => model.RequestedAction)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.CustomerComments):
        </td>
        <td class="adminData">
            @Html.TextAreaFor(model => model.CustomerComments, new { style = "Width: 500px; Height: 150px;" })
            @Html.ValidationMessageFor(model => model.CustomerComments)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.StaffNotes):
        </td>
        <td class="adminData">
            @Html.TextAreaFor(model => model.StaffNotes, new { style = "Width: 500px; Height: 150px;" })
            @Html.ValidationMessageFor(model => model.StaffNotes)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.CreatedOn):
        </td>
        <td class="adminData">
            @Html.DisplayFor(model => model.CreatedOn)
        </td>
    </tr>
</table>